"""add choices to assessment questions

Revision ID: f50a94890b75
Revises: 2b0047758102
Create Date: 2026-06-21 15:23:32.290531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50a94890b75'
down_revision: Union[str, Sequence[str], None] = '2b0047758102'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessment_answers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'assessment_answers', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assessment_answers', type_='foreignkey')
    op.drop_column('assessment_answers', 'user_id')
    # ### end Alembic commands ###
